### ISSUE TITLE
ruTorrent does not start

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#4227]
### Setup
_Package Name:_ ruRorrent
_Package Version:_ 3.10 (unreleased)

_NAS Model:_ 
_NAS Architecture:_ `apollolake`
_DSM version:_ 6.2.3

### Expected behavior
Should start.

### Actual behavior
Daemon does not start-up

### Related issues
* [ ] #3835 ruTorrent for rtd1296 / DS218play - `aarch64` (i.e. `armv8`)
* [ ] #3699 rutorrent .spk installed, but gibberish in browser - `x64`
* [ ] #3547 Rutorrent not showing up in DS1819+ - `x64`
* [ ] #3457 ruTorrent for Apollolake on DS 918+  - `x64`
* [ ] #3370 ruTorrent problems  - `x64`
* [ ]  #3062 rutorrent's mistake: rss with https problem 
* [ ] #2862 Problem with rutorrent, torrents doesn't appear as completed - `x64`
* [ ] #2221  [REQUEST] autodl-irssi for rutorrent 
* [ ] #2215  Rutorrent and DSM6 compatibility

**Comment by th0ma7** [comment]
Fixing the `/var/packages/rutorrent/target/var/.rtorrent.rc` by removing or commenting deprecated option `http_cacert` allows rutorrent to start and accessible from a web browser at: http://`<MYNAS>`/rutorrent/

Getting a few errors from the interface but the most obvious ones are related to PHP.  By digging into the `spksrc` code I noticed that `tt-rss` seems to be in a good shape and recently edited.  Would you @smaarn be availble to help me out on updating the php section of `rutorrent` spk in order to make that section functional?  I believe it never got updated between old DSM-5.x until now.
![rutorrent-start-errors](https://user-images.githubusercontent.com/17141866/96529160-6ff6de00-1252-11eb-9b45-799daa195d85.png)

**Comment by th0ma7** [comment]
@hgy59 or @ymartin59 or others, would you know how to grant permissions from a web service under ` /var/services/web/rutorrent` to specific binaries such as `ffmpeg`, `curl`, `sox`, `mediainfo`.

To me the most obvious examples are `/usr/local/rutorrent/bin/curl` and `/usr/local/ffmpeg/bin/ffmpeg` but really having no clue where to start with.

**Comment by BenjV** [comment]
I think the package is broken (or never updates to DSM 6), it does not even have a "service-setup" script so is does not create a "sc-rutorrent" user nor is it added to the "sc-download" group te be able to grant privileges.

It probably never was able to be used as of  DSM 6 as it also is still a beta package.

**Comment by th0ma7** [comment]
> I think the package is broken (or never updates to DSM 6), it does not even have a "service-setup" script so is does not create a "sc-rutorrent" user nor is it added to the "sc-download" group te be able to grant privileges.
> 
> It probably never was able to be used as of DSM 6 as it also is still a beta package.

I think @BenjV you are completely right.  Making things to compile was sort of an easy win for me as I was tired of seeing it fail in github-action but clearly it needed much more love :)  I never had a chance to look into migrating older packages to newer framework.  I'll have a shot at it.

Any advice before I begin?  Would it be worth re-starting from a good example than trying to migrate the existing?  Any package I should look into as a good example and/or documentation to look for?  Web app, php access, needs access to binaries for executions, needs directory access to deposit files and all?

Thnx in advance.

**Comment by BenjV** [comment]
Take a look at this first to comply to the current (DSM6) package standards (or ask @ymartin59 )
https://github.com/SynoCommunity/spksrc/wiki/Service-Support.
Furthermore you could take a look at Deluge.

**But the best advise I could give you is to get rid of ru-torrent.**
It is just another gui written in php and java for the libtorrent library (just like Deluge) and not a very good one too.
It is here still only in Beta available and is does not work on DSM 6 so a doubt many people are using it.

There is already Transmission and Deluge so why add another BitTorrent client?

If you want to spend energy on a BitTorrent client, you would do far better to create a package for qBittorent which is a much better torrent client also based on the libtorrent library.

**Comment by ymartin59** [comment]
I agree with @BenjV - we both (@th0ma7 and I) tried to get it run and fail - I do not think it is worth so much effort.

**Comment by smaarn** [comment]
All apologize for answering so late. I'll try having a look over the week-end see if it's really expensive (depending on 5 compatibility constraints and python constraints it could become awkward)

**Comment by th0ma7** [comment]
> I'll try having a look over the week-end see if it's really expensive (depending on 5 compatibility constraints and python constraints it could become awkward)

I tend to agree with @BenjV and @ymartin59 and perhaps we should just get rid of ruTorrent considering other alternatives?

If you find out that this may end-up being a relative "easy-win" to fix / migrate the package then so be it!  More package we have available more visibility it provides to the community... as long as it is maintainable.  Also, @smaarn feel free to reach out to me if you need some help.

**Comment by smaarn** [comment]
Ok @th0ma7 there was a relative "easy-win" to fix the package (thus the corresponding PR).

Now, from a more "serious" perspective there may be concern about the long term goal here. For example, if you take `rutorrent` it only supports officially the `rtorrent` version `0.8.2`. It therefore doesn't configure it appropriately (there would be some need to contribute to `rutorrent` to support it).

There is one "last" warning which is about the `sox` binary (it's used to "preview" audio files sound waves...).

What I tested was to basically add a torrent and check it would be downloading fine.

**Comment by QmwJlHuSg9pa** [comment]
My two cents, as a user without Docker (Qoriq arch.): Either qBittorrent or RTorrent (CLI or GUI) would be ideal. The Deluge package seems to be built for Python2 only and so doesn't support Python3 plugins, e.g. [ltConfig](https://forum.deluge-torrent.org/viewtopic.php?t=42887).

**Comment by th0ma7** [comment]
> Ok @th0ma7 there was a relative "easy-win" to fix the package (thus the corresponding PR).

You rock :)

> Now, from a more "serious" perspective there may be concern about the long term goal here. For example, if you take `rutorrent` it only supports officially the `rtorrent` version `0.8.2`. It therefore doesn't configure it appropriately (there would be some need to contribute to `rutorrent` to support it).

I looked at the requirement page at https://github.com/Novik/ruTorrent/wiki and it says the following:
- `rtorrent` 0.8.2 or later, compiled with `xmlrpc-c` support. If you don't know where to get it for your system, you are suggested to visit rtorrent official site.
- Web-server with PHP 5 

> There is one "last" warning which is about the `sox` binary (it's used to "preview" audio files sound waves...).

And what is the issue related to it?  I'm not familiar with it.
 
> What I tested was to basically add a torrent and check it would be downloading fine.

Later this week once I have a few spare cycles I'll have a try at your PR and see how things fly.  I noticed from your comments that there where still issues with initial install & update so I'll have a second look at that part for a start.

**Comment by th0ma7** [comment]
New and update to `rutorrent` version 3.10 uploaded on https://synocommunity.com/package/rutorrent
Again thnx for all your help @smaarn

**Comment by Computron010** [comment]
@th0ma7 My DS216j @ DSM 6.2.3 does not see the update, only `3.7-8`. Does it take awhile for the package to be visible in Package Center? Or is my NAS excluded from the update? Thanks!

**Comment by th0ma7** [comment]
@Computron010 it usually takes anywhere between 24-72h for the proxy to refresh.
From the arch page info https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures your NAS is an `armada38x` and package is appearing at https://synocommunity.com/package/rutorrent
